---
title: "Taylor Testing"
author: "Taylor Blair"
date: "5/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries


```{r cars}
library(tidyverse)

```

# Loading data

```{r pressure, echo=FALSE}
wsb_dd_submissions <- read_csv("Data/wsb_dd_submissions.csv")
merged_common <- read_csv("Dev/data-prep/merged_common.csv")

```



# Field plot

```{r}
library(tidyverse)

ticker_to_field <- function(ticker){
    sector <- match(ticker, tickers$Symbol, nomatch = -1)
    if (sector==-1||is.na(tickers$Sector[sector])){
        return("Other")
    }
    return(tickers$Sector[sector])
}

pivot_sector <- function(df, input_col, output_col){
    df <- df[c(input_col, output_col)]
    df <- df[!(is.na(df[[input_col]]) | df[[input_col]]==""), ] #removes empty rows
    df <- separate_rows(df, `input_col`, sep=" ") # seperates out if multiple stocks
    
    stocks <- str_c("\\b", tickers$Symbol, "\\b", collapse="|") #makes a regex of all stocks
    print(df[[input_col]])
    
    df$sector <- str_replace_all(df[[input_col]], stocks, ticker_to_field) #replaces stocks with sectors
    print(df[["sector"]])
    return(df[c("sector", output_col)]) #returns target and sector
}


```

```{r}

input_is <- "title_stocks"

sentiment_is <-"score"

wsb_dd_submissions %>%
            # filter(created_utc >= as.Date(input$sectorCreateRange[1]),
            #        created_utc <= as.Date(input$sectorCreateRange[2])) %>%
  sample_n(5000) %>%
            pivot_sector(input_is, sentiment_is) %>%
            ggplot(aes_string(x="sector", y=sentiment_is)) +
            coord_flip() +
            geom_boxplot() +
            #geom_jitter(width = 0.25, alpha = 0.3) +
            labs(y=sentiment_is, 
                 x="Sector")


```

```{r}

ticker_to_field <- function(ticker){
  sector <- match(ticker, merged_common$Symbol)
  sector <- merged_common$Sector[sector]
  if (is.na(sector)){
    return("Other")
  }
  return(sector)
}


pivot_sector <- function(df, input_col, output_col){
  df <- df %>%
    select(input_col, output_col) #grabs two target columns
  df <- df[!(is.na(df[[input_col]]) | df[[input_col]]==""), ] #removes empty rows
  df <- separate_rows(df, `input_col`, sep=" ") # seperates out if multiple stocks
  
  stocks <- str_c("\\b", merged_common$Symbol, "\\b", collapse="|") #makes a regex of all stocks
  
  df$sector <- str_replace_all(df[[input_col]], stocks, ticker_to_field) #replaces stocks with sectors
  

  return(df[c("sector", output_col)]) #returns target and sector
}

facetable_output <- c("title_sentiment", "post_sentiment", "score", "num_comments", "count_awards")
readable_facet_output <- c("Title Sentiment", "Post Sentiment", "Score", "Number of Comments", "Number of Awards")

outputted_value <- "Score"

output_on <- facetable_output[match(outputted_value, readable_facet_output)]



facetable_input <- c("title_stocks", "post_stocks")
readable_facet_input <- c("Stocks in Title", "Stocks in Selftext")

inputted_value <- "Stocks in Title"

input_on <- facetable_input[match(inputted_value, readable_facet_input)]


test <- replace_field(head(wsb_dd_submissions, 1000), input_on, output_on)



```


```{r}


wsb_dd_submissions %>%
  sample_n(100) %>%
  pivot_sector(input_on, output_on) %>%
ggplot(aes(x=reorder(sector, score, FUN = mean), y=!!output_on)) +
  coord_flip() +
  geom_boxplot(outlier.shape=NA) +
  geom_jitter(width = 0.25, alpha = 0.3) +
  labs(y=outputted_value, x="Sector", )

```



```{r}


count_and_sent <- function(df){
  
  sentiment_of_stock <- function(ticker){
    filtered_rows <- df%>%
      filter(grepl(paste("\\b", ticker, "\\b"), title_stocks))
    return(mean(filtered_rows$title_sentiment))
  }
  
stocks <- df$title_stocks[!is.na(df$title_stocks)]
stocks <- paste(stocks, sep = " ")
stocks <- as.list(unlist(strsplit(stocks, '[[:space:]]')))
stocks <- unlist(stocks)
stocks <- stocks[-(0:30)]

grouped <- tibble("stock" = stocks) %>%
  group_by(stock) %>%
  summarise(mentions=n())

grouped$sentiment <- unlist(map(grouped$stock, sentiment_of_stock))
grouped$sentiment[is.nan(grouped$sentiment)] <- 0 

return(grouped)
}

test <- count_and_sent(wsb_dd_submissions)



```

```{r}
library(openair)
library(lubridate)

wsb_dd_submissions <- read_csv("Data/wsb_dd_submissions.csv")


wsb_dd_submissions %>%
  mutate(created_utc = as.POSIXct(strptime(created_utc, format="%s")),
         created_utc = floor_date(created_utc, unit="day")) %>%
  group_by(created_utc) %>%
  summarise(posts = n()) %>%
  rename(date=created_utc) %>%
  calendarPlot(main = "Posts per day",
               pollutant = "posts")


```

